---
title: "Analysis of Canadian Mining Assets"
author: "Craig A. Sloss"
date: "2023-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Data


```{r cars}
library(dplyr)
```

The data were obtained from https://natural-resources.canada.ca/maps-tools-and-publications/publications/minerals-mining-publications/canadian-mining-assets/canadian-mining-assets-cma-country-and-region-2020-and-2021/15406. The table was copy-pasted into a CSV file, and the column headers were manually renamed to facilitate importing the data.

```{r}
mining_data_raw = read.csv("./mining_data.csv")
```

```{r}
mining_data_raw %>% nrow()
```

```{r}
continents = c("AFRICA",
               "AMERICAS (EXCLUDING CANADA)",
               "ASIA",
               "EUROPE",
               "OCEANIA")
regions = c("Eastern Africa",
            "Middle Africa",
            "Northern Africa",
            "Southern Africa",
            "Western Africa",
            "Caribbean",
            "Central America",
            "North America (excluding Canada)",
            "South America",
            "Central Asia",
            "Eastern Asia",
            "Southeastern Asia",
            "Southern Asia",
            "Western Asia",
            "Eastern Europe",
            "Northern Europe",
            "Southern Europe",
            "Western Europe",
            "Australia",
            "Melanesia",
            "New Zealand")
total = c("TOTAL FOR CANADIAN MINING ASSETS ABROAD",
          "TOTAL FOR CANADIAN MINING ASSETS")
```

```{r}
mining_data_clean = mining_data_raw %>%
  mutate(location_type = case_when(
    location %in% continents ~ "Continent",
    location %in% regions ~ "Region",
    location %in% total ~ "Total",
    TRUE ~ "Country"
  ),
  value_2020 = case_when(
    value_2020 == "–" ~ 0,
    value_2020 == "X" ~ NA,
    TRUE ~ as.numeric(gsub(",", "", value_2020))),
  value_2021 = case_when(
    value_2021 == "–" ~ 0,
    value_2021 == "X" ~ NA,
    TRUE ~ as.numeric(gsub(",", "", value_2021)))) %>%
  select(-number_of_companies_2020, -number_of_companies_2021)
```

Add an indicator column for entries corresponding to Africa. This approach is based on the fact that African entries are the first 35 entries in the data, and is not a rigourous way to define this.

```{r}
africa_ind = c(rep(TRUE, 35), rep(FALSE, 88))
mining_data_clean_2 = mining_data_clean %>% 
  mutate(africa_ind = africa_ind,
         afro_descendent_ind = location %in% c("Colombia", "Venezuela", "Brazil", "Caribbean"),
         africa_or_afro_descendent = africa_ind | afro_descendent_ind)
```


```{r}
mining_data_export = mining_data_clean_2 %>%
  filter(location_type != "Other")
```

```{r}
summary(mining_data_export)
```

```{r}
saveRDS(mining_data_export, "./mining_data_processed.rds")
```

